
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Serie1_201700343;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int truee = 8;
  public static final int div = 5;
  public static final int falsee = 9;
  public static final int coma = 7;
  public static final int cadena = 11;
  public static final int chara = 12;
  public static final int EOF = 0;
  public static final int menos = 3;
  public static final int puntoyc = 6;
  public static final int numero = 10;
  public static final int error = 1;
  public static final int por = 4;
  public static final int mas = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "menos",
  "por",
  "div",
  "puntoyc",
  "coma",
  "truee",
  "falsee",
  "numero",
  "cadena",
  "chara"
  };
}

