
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package olc1.examenfinal_201700343;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int para = 2;
  public static final int numero = 5;
  public static final int error = 1;
  public static final int coma = 4;
  public static final int parc = 3;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "para",
  "parc",
  "coma",
  "numero"
  };
}

